# -*- coding: utf-8 -*-
ITINS = [
 {"key":"one-day","title":"One day","deck":"North End to the South End, on foot. The day that shows why Boston argues about cannoli.",
  "who":"You have one day. Everything is walkable or one T stop; book one dinner.",
  "book":"Book one thing: dinner at Toro (Resy) or Pammy's (Resy, across the river).",
  "days":[{"label":"The day","stops":[
   ("8:00","Flour (Fort Point or Back Bay)","Joanne Chang's sticky bun and a coffee. Walk-in; the Fort Point original is the one."),
   ("9:30","North End","Caffè Vittoria for an espresso under the 1929 tin ceiling, then the Paul Revere House and Old North Church before the tour groups."),
   ("12:00","Galleria Umberto (North End)","Sicilian squares and arancini, cash only, until they sell out around one. Then the cannoli: Modern or Mike's — pick a side, take it to the waterfront."),
   ("2:00","Neptune Oyster (North End)","The hot buttered lobster roll at the marble bar. Walk-in only; the wait is real, put your name down and wander."),
   ("4:00","The Wig Shop (Downtown Crossing)","Through the wig shop. One cocktail, then walk the Common to Beacon Hill."),
   ("6:00","Hecate (Back Bay)","Beneath Krasi — 50 Best entry, Greek wine and cocktails. Resy."),
   ("7:30","Toro (South End)","Ken Oringer and Jamie Bissonnette's tapas room, still the loudest and best in the South End. Resy. Backup: Coppa two blocks over (walk-in) or Bar Mezzana (Resy)."),
   ("10:00","Wally's Cafe (South End)","Jazz since 1947, a few dollars at the door, cash at the bar."),
  ]}]},
 {"key":"three-day","title":"Three days","deck":"The city, then Cambridge and Somerville, then the Seaport and Southie. One side of the river a day.",
  "who":"A long weekend. Day one is the one-day plan; day two crosses the Charles; day three ends on the water.",
  "book":"Book three dinners the day reservations open: Toro, Pammy's, and O Ya or Fox & the Knife.",
  "days":[
   {"label":"Day 1 · The city","stops":[("All day","Follow the one-day plan","Flour, the North End, Neptune, the Wig Shop, Hecate, Toro, Wally's.")]},
   {"label":"Day 2 · Cambridge & Somerville","stops":[
     ("9:00","Sofra (Watertown line)","Maura Kilpatrick's Turkish pastries and a Turkish coffee. Walk-in; the morning bun sells out."),
     ("11:00","Harvard Square","Mr. Bartley's for a burger if you're hungry already; L.A. Burdick for drinking chocolate if not."),
     ("1:00","Pagu (Central Square)","Tracy Chang's Japanese-Spanish lunch — a Bib. Resy. Or Jahunger (Uyghur, Bib) if you want the surprise."),
     ("3:00","Toscanini's (Central Square)","Burnt caramel. The best ice cream in the city, and it's not close."),
     ("5:00","Bow Market (Union Square, Somerville)","Remnant Brewing in the courtyard, the shops around it. Then Backbar, through the hallway."),
     ("7:30","Pammy's (Cambridge)","The room Michelin called 'recommended' and everyone else calls the best in Cambridge. Resy, 30 days. Backup: Giulia (Resy) or Sarma (Resy, meze in Somerville)."),
     ("10:00","The Sinclair or Lizard Lounge","A show, if there is one; otherwise Charlie's Kitchen upstairs for the jukebox."),
   ]},
   {"label":"Day 3 · Seaport & Southie","stops":[
     ("9:00","Lincoln Tavern (South Boston)","The Southie brunch. Resy, or a wait."),
     ("11:00","Castle Island","Walk the loop, then Sullivan's for a hot dog and a soft serve — a James Beard America's Classic."),
     ("1:30","James Hook & Co (Seaport)","A lobster roll on the pier."),
     ("3:00","Trillium Fort Point","The rooftop, a beer, the harbor."),
     ("5:00","Drink (Fort Point)","No menu; tell them what you like. Walk-in; go early."),
     ("7:30","O Ya (Leather District) or Fox & the Knife (South Boston)","O Ya for Tim Cushman's omakase (Tock; the splurge); Fox & the Knife for Karen Akunowicz's Bib-winning pasta (Resy). Backup: Row 34 (Resy)."),
     ("10:00","Lookout Rooftop (The Envoy)","The skyline across the channel, one last drink."),
   ]},
  ]},
 {"key":"five-day","title":"Five days","deck":"The three-day plan, plus the North Shore clam trail and one day for the counters.",
  "who":"Enough time to leave the city: fried clams in Essex, roast beef on Revere Beach, and the tasting counters back in town.",
  "book":"Set alarms for 311 Omakase (Tock), O Ya (Tock), Toro and Pammy's.",
  "days":[
   {"label":"Days 1–3","stops":[("All","Follow the three-day plan","The city, Cambridge and Somerville, the Seaport and Southie.")]},
   {"label":"Day 4 · The North Shore","stops":[
     ("9:00","Kane's Donuts (Saugus)","The honey dip, on the way north. Cash-friendly, walk-in."),
     ("11:00","Woodman's of Essex","Where the fried clam was invented in 1916. Whole-belly, with the tartar. Walk-in; the line is the ritual."),
     ("1:30","Rockport","Roy Moore Lobster Co on Bearskin Neck — a lobster on the back deck. Cash."),
     ("4:00","Kelly's Roast Beef (Revere Beach)","On the way back: the roast beef sandwich that started the North Shore's rivalry, eaten on the seawall."),
     ("6:00","Santarpio's (East Boston)","Pizza since 1903, lamb tips from the grill, cash only. Walk-in."),
     ("8:00","Kowloon (Saugus)","The Route 1 tiki palace. Scorpion bowls. You've earned it."),
   ]},
   {"label":"Day 5 · The counters","stops":[
     ("10:00","The Paramount (Beacon Hill)","The line, the pancakes. Cash-friendly, walk-in."),
     ("12:00","Boston Public Market → Haymarket","The market hall, then the Friday–Saturday produce market that's been shouting since 1830."),
     ("2:00","Union Oyster House","Oysters at the bar where Daniel Webster ate — America's oldest restaurant, 1826. Walk-in at the bar."),
     ("4:00","Contessa (The Newbury)","One drink under the glass roof. Resy."),
     ("6:00","Offsuit (Leather District)","Behind Troquet, reservation only, the quietest good bar in the city."),
     ("8:00","311 Omakase ★ (South End)","Boston's first Michelin star: Wei Fa Chen's counter in a rowhouse. Tock, weeks out. Alternative: Uni at the Eliot (Resy; Ken Oringer's sashimi bar) or Mooncusser's seafood tasting (Resy)."),
     ("11:00","Bova's (North End)","Open 24 hours. A cannoli for the road."),
   ]},
  ]},
]
GOTCHAS = [
 ("Reservations, and the walk-in bars.", "Resy rooms release 30 days out at 9 or 10am; Tock counters (311 Omakase, O Ya, Tasting Counter) in blocks. Neptune, Galleria Umberto, Drink and the North End caffès don't take reservations — arrive early or accept the wait."),
 ("Cash is the North End's language.", "Galleria Umberto, Santarpio's, Kelly's, Roy Moore, Wally's and most of Haymarket are cash-only or cash-first. Modern and Mike's take cards but the line moves faster with bills."),
 ("Tip 20%; tax is 7%.", "Massachusetts meals tax is 6.25% plus a local 0.75% in Boston; menus exclude it. Tip 18–22% on the pre-tax total. Some restaurants add a kitchen appreciation fee — read the bill."),
 ("Last call is 2am, and the T stops before that.", "Bars close at 2am (some at 1am). The T's last trains leave downtown around 12:30am — after that it's a car. Cambridge and Somerville are a short, cheap ride."),
 ("Winter is real; so is patio season.", "Rooftops and beer gardens run May through October; the Envoy's Lookout does winter igloos. Fried-clam shacks on the North Shore close for the season — Woodman's stays open, the Clam Box doesn't always."),
 ("Sunday and Monday closures.", "Many chef-owned rooms close one or both — Pammy's, Sarma, Juliet, Oleana all do at least one. The North End runs seven days."),
 ("The cannoli question.", "Mike's is the famous one; Modern is the one locals send you to; Maria's makes the best sfogliatelle. Bova's is open at 2am. The correct answer is to try two."),
 ("Fried clams: whole-belly, or don't.", "Strips are for people who don't like clams. Order whole-belly, with tartar, and expect to pay $30+ — clam prices have doubled since 2020."),
 ("Use the Amex credit like a local.", "Platinum $100 per quarter, Gold $50 twice a year, at any Resy or Tock venue showing the 'Resy Credit eligible' badge — no booking through Resy required."),
 ("Anything marked verify, verify.", "Boston lost a run of beloved rooms — the Middle East, Great Scott, Doyle's, Craigie, Island Creek Kenmore. A minute on Resy or Google before you cross the river."),
 ("Roast beef: the three-way.", "On the North Shore a 'three-way' is roast beef with barbecue sauce, mayo and American cheese on an onion roll. Kelly's is the original; Nick's and Bill & Bob's are the fights."),
 ("One for the road.", "Logan's Terminal B has a Legal Sea Foods and Terminal C a Dunkin'. South Station has Pavement and, for the train, a Flour box across the street."),
]
