# -*- coding: utf-8 -*-
ITINS = [
 {"key":"one-day","title":"One day","deck":"The Loop to Logan Square. A depression dog at noon, a Bib at eight, jazz in Capone's booth at eleven.",
  "who":"One day, on the L. Book one dinner.",
  "book":"Book one thing: dinner at Galit (Resy) or Kasama's tasting menu (Tock).",
  "days":[{"label":"The day","stops":[
   ("8:00","Lou Mitchell's (West Loop)","Since 1923, the free Milk Duds at the door, the omelet in the skillet. Walk-in; the line is the ritual."),
   ("9:30","The Loop","The Art Institute or the architecture boat tour — the boat is the one to book. Garrett Popcorn's Chicago mix on the way."),
   ("12:00","Gene & Jude's (River Grove) or Al's Beef (Little Italy)","The depression dog (mustard, relish, onions, sport peppers, fries on top — no ketchup) is 25 minutes west; the dipped Italian beef is ten minutes south. Pick one. Cash is fastest at both."),
   ("2:00","Pequod's (Lincoln Park)","One pan, the caramelized cheese crust — the deep dish locals actually eat. Walk-in; order the moment you sit."),
   ("4:00","The Violet Hour (Wicker Park)","Behind the mural, no sign, the bar that started Chicago's cocktail revival. Walk-in; go early. Then Dorian's through the record shop next door."),
   ("6:00","Cindy's (Chicago Athletic Association)","One drink over Millennium Park at golden hour. Resy. If it's full, the Milk Room downstairs — eight seats, vintage spirits."),
   ("7:30","Galit (Lincoln Park) ★ or Kasama (Ukrainian Village) ★★","Galit for Zach Engel's Middle Eastern (Resy, 30 days); Kasama for the Filipino tasting menu that just earned its second star (Tock). Backup: Daisies (Logan Square, Bib + Green Star, Resy) or Lula Cafe (Resy)."),
   ("10:30","Green Mill (Uptown)","Jazz since 1907, Capone's booth, a Malört if you dare. Cash at the door."),
  ]}]},
 {"key":"three-day","title":"Three days","deck":"The Loop and Lincoln Park, then the West Side, then the South Side. One direction a day.",
  "who":"A long weekend. Day one is the one-day plan; day two is Fulton Market and Logan Square; day three goes south.",
  "book":"Book three dinners the day reservations open: Galit or Kasama, Smyth or Oriole, and Virtue.",
  "days":[
   {"label":"Day 1 · The Loop & Lincoln Park","stops":[("All day","Follow the one-day plan","Lou Mitchell's, the Loop, a dog or a beef, Pequod's, the Violet Hour, Cindy's, Galit, the Green Mill.")]},
   {"label":"Day 2 · West","stops":[
     ("9:00","Kasama (Ukrainian Village)","The morning bakery-café — ube pastries and the longganisa breakfast sandwich. Walk-in; the line moves."),
     ("11:00","Fulton Market","Publican Quality Bread for a loaf to carry, Time Out Market for a look, Sawada's military latte in the West Loop."),
     ("1:00","Au Cheval (West Loop)","The burger. Walk-in, put your name down, expect an hour — or Monteverde for Sarah Grueneberg's pasta (Resy) if you can't wait."),
     ("3:30","Logan Square","The Bib row on foot: Lardon for a charcuterie plate, Cellar Door for a glass, Margie's Candies for a sundae if you've room."),
     ("5:30","Best Intentions or Meadowlark (Logan Square)","Both 50 Best; both walk-in early. Scofflaw for gin if you want a third."),
     ("7:30","Smyth (West Loop) ★★★ or Oriole (West Loop) ★★","Smyth for the only three stars in the city (Tock, weeks out); Oriole through the freight elevator (Tock). Backup: Elske ★ (West Loop; Resy) or Rose Mary (Fulton Market, Bib, Resy)."),
     ("10:30","Kumiko (West Loop)","Julia Momosé's bar — 2024 James Beard Outstanding Bar. Resy; the counter takes walk-ins late."),
   ]},
   {"label":"Day 3 · South","stops":[
     ("9:30","Manny's (South Loop)","Corned beef on rye at the cafeteria line, since 1942. Walk-in."),
     ("11:00","Pilsen","The murals on 18th Street, then Carnitas Uruapan for a pound of carnitas by weight, since 1975. Cash."),
     ("1:00","Chinatown","MingHin for dim sum, Qing Xiang Yuan for dumplings, Chiu Quon for egg tarts on the way out. Walk-in."),
     ("3:00","Bridgeport","Maria's Packaged Goods — a liquor store that's also the best bar on the South Side — and Kimski next door for Korean-Polish."),
     ("5:00","Hyde Park","Valois cafeteria for the atmosphere, the Robie House for the architecture, Plein Air for a coffee."),
     ("7:30","Virtue (Hyde Park)","Erick Williams' Southern room, a Bib and a James Beard Best Chef. Resy. Backup: Lem's Bar-B-Q rib tips in Chatham (walk-in, cash), then Calumet Fisheries for smoked shrimp if you have a car."),
     ("10:00","Buddy Guy's Legends (South Loop)","The blues, where it lives. Cover at the door."),
   ]},
  ]},
 {"key":"five-day","title":"Five days","deck":"The three-day plan, plus the North Side neighborhoods and a day for the counters and the lake.",
  "who":"Enough time to eat like a resident: Devon Avenue, Uptown's Asian blocks, a tasting counter, and the lakefront.",
  "book":"Set alarms for Smyth, Alinea or Ever (Tock), Kasama, and Schwa's phone line.",
  "days":[
   {"label":"Days 1–3","stops":[("All","Follow the three-day plan","The Loop, the West Side, the South Side.")]},
   {"label":"Day 4 · North","stops":[
     ("9:00","Lost Larson (Andersonville)","Cardamom buns and the Scandinavian case. Walk-in."),
     ("11:00","Devon Avenue","The Indian-Pakistani strip: Sabri Nihari for the nihari, Uru-Swati for the vegetarian thali, the sweet shops between. Cash is fastest."),
     ("1:30","Uptown","Sun Wah for the Beijing duck ceremony (order it when you sit — it takes time), or Birrieria Zaragoza for the goat (Bib). Then the Green Mill by day for the room."),
     ("4:00","Hopleaf (Andersonville)","Belgian beer and the mussels; the back garden if it's warm. Walk-in."),
     ("6:30","Cariño (Uptown) ★","Norman Fenton's Latin tasting counter. Resy. Backup: Nadu (Lincoln Park; South Indian, Bib, Resy) or Boonie's (Filipino, Bib)."),
     ("9:30","Carol's Pub (Uptown)","Honky-tonk, live country, cash. Or the Whistler in Logan Square for jazz in a tiny room."),
   ]},
   {"label":"Day 5 · The counters, and the lake","stops":[
     ("10:00","Lula Cafe (Logan Square)","The Sunday brunch that defined Chicago's neighborhood restaurant, since 1999. Resy, or a wait."),
     ("12:30","The lakefront","Rent a bike on the Lakefront Trail from North Avenue Beach to Montrose. Castaways or the Dock for a beer if it's summer."),
     ("3:30","Offshore (Navy Pier)","The largest rooftop bar in the world, for one drink and the skyline. Resy."),
     ("5:30","Schwa (Wicker Park) ★ — the phone","Call. Keep calling. If Michael Carlson answers and has a seat, cancel everything else. Otherwise —"),
     ("8:00","Alinea ★★ or Ever ★★ or Next ★","Alinea for Grant Achatz's theater (Tock; the Salon is the accessible seat); Ever for Curtis Duffy and the best service in the city (Tock); Next for whatever the menu is this season (Tock). All weeks out. Backup: Esmé ★ (Lincoln Park; Tock)."),
     ("11:00","Smartbar (Wrigleyville)","Beneath Metro, since 1982, the best sound system in the city. Or the Milk Room if you'd rather end quietly."),
   ]},
  ]},
]
GOTCHAS = [
 ("Tock was invented here — learn it.", "Alinea's co-founder built Tock, so the tasting counters (Alinea, Smyth, Ever, Oriole, Next, Kasama, Schwa's neighbors) sell tickets in blocks, often prepaid and non-refundable. Set alerts. Resy runs the rest, 30 days out. Schwa takes reservations by phone only; the line is legendary."),
 ("Deep dish vs tavern-style.", "Tourists eat deep dish (Lou Malnati's, Pequod's, Giordano's); Chicagoans eat tavern-style — thin, square-cut, from Vito & Nick's, Pat's, Marie's. Try both. Never call deep dish 'a pie' out loud."),
 ("No ketchup on a hot dog.", "The Chicago dog is mustard, relish, onion, tomato, pickle, sport peppers, celery salt on a poppy-seed bun. The depression dog (Gene & Jude's) skips the tomato and pickle and adds fries. Asking for ketchup will be noted."),
 ("Cash at the stands.", "Gene & Jude's, Jim's Original, Johnnie's Beef, Carnitas Uruapan, most of Devon and Maxwell Street Market, and the Green Mill's door are cash-first. Carry $60 on the neighborhoods days."),
 ("Tip 20%; tax is 11.75% downtown.", "Chicago's restaurant tax is among the highest in the country — 10.75% citywide, 11.75% in the downtown zone. Menus exclude it. Some restaurants add a service charge; read the bill."),
 ("The L runs all night on two lines.", "The Red and Blue lines run 24 hours; the others stop around 1am. Tap in with a contactless card (Ventra is optional). Late in Logan Square or Pilsen, the Blue and Pink lines get you home; the South Side after midnight is a car."),
 ("Winter is the point, and the problem.", "November to March the rooftops, the Riverwalk and the beach bars close; the Green Mill, the steakhouses and the tasting rooms don't. Summer is the season: Ravinia, the lakefront, Wrigley bleachers, Maxwell Street on Sunday."),
 ("Monday is dark.", "Alinea, Smyth, Oriole, Ever, Kasama's tasting menu and most chef rooms close Sunday and Monday. The hot-dog stands, Chinatown and the taverns run seven days."),
 ("Use the Amex credit like a local.", "Platinum $100 per quarter, Gold $50 twice a year, at any Resy or Tock venue showing the 'Resy Credit eligible' badge. Tock's counters now count — a prepaid Alinea ticket is the easiest $100 you'll spend."),
 ("Anything marked verify, verify.", "Chicago lost Berlin, Double Door, Lost Lake, Passerotto, Fat Rice and Xoco within a few years. A minute on Resy or Google before you take the L across town."),
 ("Malört.", "Jeppson's Malört is a wormwood liqueur that tastes like regret. A shot will be offered to you at some point as a test. Take it once."),
 ("One for the road.", "O'Hare's Terminal 3 has a Tortas Frontera (Rick Bayless) that is the best airport food in America; Terminal 1 has Garrett's. Midway has a Harry Caray's and a Nuts on Clark."),
]
