# -*- coding: utf-8 -*-
ITINS = [
 {"key":"one-day","title":"One day","deck":"East side to Downtown. A truck at noon, a Bib at eight, Koreatown after midnight.",
  "who":"One day, one car. LA is a driving city; plan by neighborhood, not by list. Book one dinner.",
  "book":"Book one thing: dinner at Kismet (Resy) or Bestia (Resy).",
  "days":[{"label":"The day","stops":[
   ("8:30","Go Get Em Tiger (Larchmont)","The coffee that set LA's standard, and a breakfast burrito. Walk-in."),
   ("10:00","République (La Brea)","The pastry case, for the road — or sit, for the eggs. Walk-in; the line moves."),
   ("12:00","Mariscos Jalisco (Boyle Heights)","The shrimp taco truck: crispy, dorado, with avocado and salsa, from a window on Olympic. Cash. The best $4 in the city."),
   ("1:30","Grand Central Market (DTLA)","Sarita's for a pupusa, Villa Moreliana for carnitas, Eggslut if you must. Then Philippe's ten minutes north for the French dip since 1908 — or Cole's, and pick a side."),
   ("3:30","The Arts District","Bread Lounge, Hauser & Wirth, a look at the Row where Kato lives. Then Everson Royce Bar for the burger and the patio."),
   ("6:00","Thunderbolt (Echo Park)","LA's 50 Best bar. Walk-in early; the patio is the seat."),
   ("8:00","Kismet (Los Feliz) or Bestia (Arts District)","Kismet for Sara Kramer and Sarah Hymanson's Middle Eastern (Bib, Resy); Bestia for the room that started the Arts District (Resy, 30 days). Backup: Pine & Crane (Bib, walk-in) or Little Fish (Bib, the new one)."),
   ("10:30","Koreatown","Dan Sung Sa for the pojangmacha, then Sun Nong Dan for galbi jjim at 1am (Bib, 24 hours). Or Tiki-Ti in Los Feliz, cash, since 1961."),
  ]}]},
 {"key":"three-day","title":"Three days","deck":"The east side, then the west, then the San Gabriel Valley. One freeway a day.",
  "who":"A long weekend. Day one is the one-day plan; day two is Hollywood to the ocean; day three goes east to the SGV.",
  "book":"Book three dinners the day reservations open: Kismet or Bestia, Providence or n/naka, and Bistro Na's.",
  "days":[
   {"label":"Day 1 · East","stops":[("All day","Follow the one-day plan","Larchmont, République, Mariscos Jalisco, Grand Central Market, the Arts District, Thunderbolt, Kismet, Koreatown.")]},
   {"label":"Day 2 · Hollywood to the ocean","stops":[
     ("9:00","Sqirl (Virgil Village)","The ricotta toast and the sorrel pesto rice bowl. Walk-in; the line is the ritual."),
     ("11:00","Musso & Frank (Hollywood)","A martini at the bar since 1919 — they open at 11. Then the sign from the flats, and Yamashiro's terrace for the view if it's clear."),
     ("1:00","Sonoratown (Mid-City)","Flour tortillas from Sonora, mesquite carne asada — a 2026 Bib. Walk-in."),
     ("3:00","Venice","Gjusta's deli counter, the canals, Abbot Kinney. Menotti's for an espresso."),
     ("5:30","The Bungalow (Santa Monica)","One drink at the Fairmont's bungalow at golden hour, the pier below. Or Chez Jay next door, since 1959."),
     ("7:30","Providence (Hollywood) ★★★ or n/naka (Palms) ★★","Providence for Michael Cimarusti's seafood — the first three-star in the city (Tock); n/naka for Niki Nakayama's kaiseki (Tock, weeks out). Backup: Felix (Venice; Resy) or Pasjoli ★ (Santa Monica; Tock)."),
     ("10:30","The Roger Room (West Hollywood)","No sign, the tarot mural. Or Bar Lis on the Thompson's roof."),
   ]},
   {"label":"Day 3 · The San Gabriel Valley","stops":[
     ("10:00","Sea Harbour (Rosemead)","Dim sum from the carts — the best in the country. Walk-in; arrive before 10:30 or wait an hour. Lunasia in Alhambra if the wait is too long."),
     ("12:30","Alhambra & San Gabriel","Hui Tou Xiang for pan-fried dumplings (Bib), Chengdu Taste for the Sichuan, Yang's Kitchen if you'd rather sit (Bib)."),
     ("2:30","Fosselman's (Alhambra)","Ice cream since 1919. Then Din Tai Fung in Arcadia, the American original, if you're still standing."),
     ("4:30","Little Tokyo","Back west: Fugetsu-Do for mochi since 1903, Mitsuru for imagawayaki, a look at the Japanese American National Museum."),
     ("7:00","Bistro Na's (Temple City) ★","Imperial Chinese with a star in a strip mall — the most SGV restaurant on the list. Resy. Backup: Newport Seafood (the lobster; walk-in) or Hayato ★★ in the Arts District (Tock) if you want the counter."),
     ("9:30","The Prince (Koreatown)","Fried chicken and the Chinatown film set. Then Break Room 86 through the back of the Line if you want to dance."),
   ]},
  ]},
 {"key":"five-day","title":"Five days","deck":"The three-day plan, plus the Valley and Thai Town, and a day for the counters and the coast.",
  "who":"Enough time to eat like a resident: Thai Town at 2am, the Valley's delis, Malibu's picnic tables, and the counters that need weeks.",
  "book":"Set alarms for Somni or Providence, Kato (Tock), and Anajak's Taco Tuesday.",
  "days":[
   {"label":"Days 1–3","stops":[("All","Follow the three-day plan","East, Hollywood to the ocean, the SGV.")]},
   {"label":"Day 4 · The Valley & Thai Town","stops":[
     ("9:00","Porto's (Burbank)","Potato balls, guava strudel, the line. Cash-friendly, walk-in."),
     ("10:30","Bob's Big Boy (Burbank)","The 1949 original; Friday night is classic-car night. Then the Warner lot or Universal if you must."),
     ("1:00","Anajak Thai (Sherman Oaks)","If it's Tuesday: Taco Tuesday, the most-argued-about meal in the Valley (Resy). Otherwise the regular menu, still a Bib and a Beard finalist."),
     ("3:30","Thai Town","Sapp Coffee Shop for boat noodles, Bhan Kanom Thai for sweets, Ruen Pair for the papaya salad (Bib)."),
     ("6:00","Tabula Rasa (Thai Town)","Natural wine and a listening bar's calm. Then Harvard & Stone next door."),
     ("8:00","Jitlada (Thai Town)","Southern Thai, spice you'll remember. Walk-in, or Resy. Then Sanamluang across the street at 2am if you're still going."),
   ]},
   {"label":"Day 5 · The coast, and the counter","stops":[
     ("10:00","Malibu","Malibu Seafood's picnic tables, or Neptune's Net with the bikers. Cash-friendly."),
     ("1:00","Nobu Malibu","Lunch on the deck if you can get it (OpenTable); Malibu Farm on the pier if you can't."),
     ("4:00","Harriet's Rooftop (1 Hotel West Hollywood) or Bar Lis (Thompson Hollywood)","One drink at golden hour."),
     ("6:00","Death & Co LA (Arts District)","The New York bar's LA room. Resy."),
     ("8:00","Somni ★★★ or Kato ★★","Somni for Aitor Zabala's fourteen seats in West Hollywood (Tock; the hardest ticket in the city); Kato for Jon Yao's Taiwanese counter, promoted in June (Tock). Alternative: Hayato ★★ (Tock) or Corridor 109 ★, the new one (Tock)."),
     ("11:00","Jumbo's Clown Room (Los Feliz)","Cash at the door. Or Canter's, 24 hours since 1931, for a pastrami on the way home."),
   ]},
  ]},
]
GOTCHAS = [
 ("You need a car. Plan by neighborhood.", "LA is not walkable between neighborhoods and the 405 is not a joke. Group each day by area — east side, the SGV, the westside — and never cross the city at 5pm. Rideshares are reliable; budget $30–50 a hop after dark. Metro's B and D lines link Downtown, Koreatown and Hollywood usefully."),
 ("Tock for the counters, SevenRooms for the scene.", "Somni, Providence, n/naka, Kato, Hayato and most omakase counters sell tickets on Tock, often weeks out and prepaid. West Hollywood's scene restaurants (Delilah, Catch, the Nice Guy) book on SevenRooms and hold tables for the house. Resy runs the neighborhood rooms, 30 days out."),
 ("Cash at the trucks and the counters.", "Mariscos Jalisco, Leo's, the Tire Shop, Tiki-Ti, Jumbo's and most of Boyle Heights and Thai Town are cash-only or cash-first. Carry $80 on the east-side day."),
 ("Tip 20%; watch the surcharges.", "Many LA restaurants add a 3–5% 'wellness' or service fee to the bill — legal if disclosed, not the tip. Sales tax on meals is 9.5–10.25% depending on the city you're standing in. Read the check."),
 ("Koreatown runs late; everything else doesn't.", "Sun Nong Dan, Sanamluang, Canter's and California Donuts are 24 hours; most of the city's kitchens close at 10. Last call is 2am statewide — no exceptions."),
 ("Monday is dark, and so is much of Sunday.", "Somni, Providence, n/naka, Hayato and most chef rooms close Sunday and Monday. The trucks, Koreatown, the SGV and the diners run seven days."),
 ("The French dip has two birthplaces.", "Philippe's and Cole's both opened in 1908 and both claim it. Philippe's is sawdust floors and 10-cent coffee; Cole's has a bar (and, maybe, the Varnish behind it). Try both; don't take a side out loud."),
 ("The SGV is a different city.", "Alhambra, San Gabriel, Rosemead, Arcadia and Temple City are 20 minutes east and have the best Chinese food in America. Go for lunch — the dim sum lines start at 10am — and bring a car with parking patience."),
 ("Use the Amex credit like a local.", "Platinum $100 per quarter, Gold $50 twice a year, at any Resy or Tock venue showing the 'Resy Credit eligible' badge. A prepaid Tock ticket at n/naka is the easiest use of it."),
 ("Anything marked verify, verify.", "LA lost the Original Pantry, Nightshade, Employees Only, the Walker Inn and Sweet Lady Jane within two years; three restaurants lost stars in June. A minute on Resy or Google before you get on the freeway."),
 ("The taco vocabulary.", "Al pastor: off the spinning trompo (Leo's). Tijuana-style: on a mesquite grill with guacamole (Tire Shop). Sonoran: flour tortillas, carne asada (Sonoratown). Dorado: fried shell, shrimp inside (Mariscos Jalisco). Order two of each; it's still under $20."),
 ("One for the road.", "LAX has a Sam First jazz club across the street and, in Terminal 2, an Eggslut. Burbank's terminal is a ten-minute drive from Porto's — buy a box."),
]
