# -*- coding: utf-8 -*-
ITINS = [
 {"key":"one-day","title":"One day","deck":"Little Havana to the Design District. Cafecito at 3:05, a two-star at eight.",
  "who":"One day, one car (or a lot of rideshares — Miami is not a walking city). Book one dinner.",
  "book":"Book one thing: dinner at Boia De (Resy) or L'Atelier (Tock).",
  "days":[{"label":"The day","stops":[
   ("8:30","Versailles ventanita (Little Havana)","A cafecito and a pastelito de guayaba at the window. Cash is fastest; stand with the regulars."),
   ("10:00","Calle Ocho","Domino Park, the cigar rollers, Los Pinareños for a batido. Sanguich for an early Cubano — a Bib, and the best sandwich in the city."),
   ("12:30","Zak the Baker (Wynwood)","The challah, a babka, and the murals of Wynwood Walls after. Walk-in."),
   ("2:30","Panther Coffee (Wynwood)","The roaster that started Miami's coffee scene. Then a look inside Hiden's unmarked door — you'll need Tock to get further."),
   ("4:30","Bar Kaiju (Little River)","Up the stairs at The Citadel — 50 Best №70. Then Dante's HiFi if you'd rather listen than talk."),
   ("6:00","Sugar (EAST, Brickell)","One drink forty floors up; the sunset over the bay is the point. Resy; go early."),
   ("8:00","Boia De (Little Haiti) ★ or L'Atelier de Joël Robuchon (Design District) ★★","Boia De for the counter and the pasta (Resy, 30 days; hardest table in the city); L'Atelier for the only two-star in Florida (Tock). Backup: Ariete ★ (Coconut Grove, Resy) or Mandolin (the garden, Bib, Resy)."),
   ("10:30","Café La Trova (Little Havana)","Julio Cabrera's cantineros dancing behind the bar, a rumba band, a daiquiri. 50 Best №42. Walk-in; the room is loud and that's the idea."),
  ]}]},
 {"key":"three-day","title":"Three days","deck":"The mainland, then the Beach, then the Grove and the river. One shoreline a day.",
  "who":"A long weekend. Day one is the one-day plan; day two is South Beach done properly; day three is the water.",
  "book":"Book three dinners the day reservations open: Boia De, Stubborn Seed, and the Surf Club or Ariete.",
  "days":[
   {"label":"Day 1 · The mainland","stops":[("All day","Follow the one-day plan","Versailles, Calle Ocho, Zak, Wynwood, Bar Kaiju, Sugar, Boia De, La Trova.")]},
   {"label":"Day 2 · The Beach","stops":[
     ("9:00","La Sandwicherie (South Beach)","The French sandwich shop since 1988, for breakfast on the alley. Then the beach, before it's hot."),
     ("12:00","Joe's Take Away (South of Fifth)","Stone crabs from the counter, no line, eaten on the sea wall. October–May only; the rest of the year, Lucali (Bib, Sunset Harbour) for pizza."),
     ("2:00","Sweet Liberty (South Beach)","Naren Young's bar, for a daiquiri and the happy-hour oysters. Walk-in."),
     ("4:00","Broken Shaker (Freehand, Mid-Beach)","The original, by the pool. Then the Faena for a look at the gold mammoth."),
     ("6:00","Champagne Bar at the Surf Club (Surfside)","The most beautiful room in Miami, for one glass. Walk-in early."),
     ("7:30","Stubborn Seed (South Beach) ★","Jeremy Ford's tasting menu, Green Star for the farm (Resy, 30 days). Backup: The Surf Club Restaurant ★ (Thomas Keller, Surfside, Resy) or Macchialina (Italian, easier, Resy)."),
     ("10:30","Mac's Club Deuce (South Beach)","The 1926 dive. Cash. Then Do Not Sit On The Furniture if you want to dance."),
   ]},
   {"label":"Day 3 · The Grove & the river","stops":[
     ("9:30","Chug's Diner (Coconut Grove)","Cuban-American breakfast — a Bib. Then the Grove's banyans and Vizcaya."),
     ("12:30","Los Félix (Coconut Grove) ★","Masa from heritage corn, a star and a Green Star, and lunch is the easy seat. Resy."),
     ("3:00","Krüs Kitchen (Coconut Grove)","A glass of something natural in the courtyard — Green Star."),
     ("5:00","Garcia's (Miami River)","Oysters and a beer on the dock, from the boats tied up beside you. Walk-in."),
     ("7:00","Kiki on the River (Miami River)","Greek, on the water, the scene. SevenRooms. Or Seaspice next door."),
     ("9:30","Ball & Chain (Little Havana)","Live music on the Pineapple stage, a mojito, the end of the night."),
   ]},
  ]},
 {"key":"five-day","title":"Five days","deck":"The three-day plan, plus the drive south and one day for the counters.",
  "who":"Enough time to leave the city — the Redland, Card Sound Road, a fruit stand — and to eat at the counters that need a reservation.",
  "book":"Set alarms for Boia De, Stubborn Seed, Ogawa or Hiden (Tock), and Cote.",
  "days":[
   {"label":"Days 1–3","stops":[("All","Follow the three-day plan","The mainland, the Beach, the Grove and the river.")]},
   {"label":"Day 4 · South","stops":[
     ("9:00","Knaus Berry Farm (Homestead)","The cinnamon rolls; the line is the ritual. November–April only. Otherwise Robert Is Here, the fruit stand, for a key lime milkshake."),
     ("11:00","Redland","Schnebly's for a mango wine, the Fruit & Spice Park, El Toro Taco for lunch."),
     ("2:00","Alabama Jack's (Card Sound Road)","Conch fritters and a beer on the water, halfway to Key Largo. Cash. Turn around here or keep driving."),
     ("6:30","Shorty's BBQ (South Miami)","Since 1951, on the way back. Walk-in."),
     ("8:30","Hometown Barbecue Miami (Allapattah)","Or, if Shorty's was lunch: the Brooklyn pitmaster's Miami room — a Bib. Then Las Rosas across the street."),
   ]},
   {"label":"Day 5 · The counters, and Sunday","stops":[
     ("10:30","Sadelle's (Coconut Grove) or Pastis (Wynwood)","The New York brunches, transplanted. Resy."),
     ("1:00","1-800-Lucky (Wynwood)","The Asian food hall for a light lunch, then the galleries."),
     ("4:00","Astra (Wynwood)","The rooftop, one drink. Resy."),
     ("6:00","ViceVersa (Downtown)","50 Best №46, aperitivo hour. Resy."),
     ("8:00","Ogawa ★ or Hiden ★","Ogawa in Little River, Hiden behind the door in Wynwood — both omakase, both Tock, both weeks out. Alternative: Cote Miami ★ (Design District; Resy) for the Korean steakhouse theater."),
     ("11:00","Club Space (Downtown)","If it's the weekend: the terrace, and the sunrise. Otherwise E11even, which never closes."),
   ]},
  ]},
]
GOTCHAS = [
 ("You need a car, or a rideshare budget.", "Miami is not walkable between neighborhoods. Brickell, Wynwood, the Beach and the Grove are 20–40 minutes apart in traffic. The Metromover is free downtown; the Metrorail reaches the Grove and Dadeland. Budget $25–40 a hop after dark."),
 ("Reservations, and the Tock counters.", "Resy rooms release 30 days out; the omakase counters (Hiden, Ogawa, Shingo, Naoe, L'Atelier) are on Tock in blocks. Boia De is the hardest table in the city — set Notify. Brickell's scene restaurants (Gekko, Sexy Fish, Komodo) book on SevenRooms."),
 ("Stone crab is seasonal.", "Mid-October to early May. Joe's is closed for the rest of the year; the takeout window skips the line. Claws are priced by size and the large ones are $100+ a plate."),
 ("Cash at the ventanitas.", "Versailles, La Carreta, Pinareños, the fritas counters and most of Hialeah move faster in cash. The 3:05pm cafecito (305, the area code) is a real thing."),
 ("Tip 20%; check for the automatic gratuity.", "Miami Beach restaurants routinely add 18–20% service to the bill — it's the law that it be disclosed, and tourists routinely tip on top of it. Read the check. Sales tax on meals is 7%, 9% on the Beach with resort fees."),
 ("Dress codes are real, and so are the doormen.", "LIV, E11even, Papi Steak, Sexy Fish and the Faena enforce them. Collared shirts and closed shoes for men; no flip-flops after dark anywhere that matters. Café La Trova and Ball & Chain don't care."),
 ("Season runs November to April.", "Art Basel week (early December) and Ultra (March) double the prices and halve the availability. Summer is hot, wet and cheaper; hurricane season is June–November and rooftops close in storms."),
 ("Monday is dark, Sunday is brunch.", "Boia De, Stubborn Seed, Ogawa and most chef rooms close Monday and often Tuesday. The Cuban places run seven days, 24 hours in some cases."),
 ("Use the Amex credit like a local.", "Platinum $100 per quarter, Gold $50 twice a year, at any Resy or Tock venue showing the 'Resy Credit eligible' badge — no booking through Resy required."),
 ("Anything marked verify, verify.", "Miami's scene turns over faster than any other city in this series — Story, Treehouse, Alter, Beaker & Gray, Employees Only all closed within two years. A minute on Resy or Google before you drive across the causeway."),
 ("The Cuban vocabulary.", "Cafecito: a shot of sweet espresso. Colada: a large cafecito with tiny cups, meant to share. Cortadito: with a splash of milk. Frita: a Cuban burger with shoestring potatoes. Croqueta: order two. Pastelito: guava and cheese is the correct one."),
 ("One for the road.", "MIA has a Versailles in Terminal D and a Café La Carreta in D too; a colada at the gate is the right way to leave."),
]
