# Reservation platform by place name (as best known, mid-2026). R=Resy T=Tock O=OpenTable S=SevenRooms W=walk-in
R = """Cosme|Union Square Cafe|Casa Mono|King|Lei|Via Carota|Le Veau d'Or|Le Rock|Libertine|Bar Pisellino|Café Boulud|Cafe Carmellini|Cafe Chelsea|Cafe Kestrel|Cafe Mars|Agi's Counter|Gertie|Runner Up|Dimes|Bar Blondeau|Lodi|Sailor|Claud|Penny|Cervo's|Roscioli NYC|Raf's|The Musket Room|Foxface Natural|Bonnie's|Golden Diner|Maison Premiere|Bar Primi|Laser Wolf|Hav & Mar|Estela|Altro Paradiso|Lord's|Tolo|Ci Siamo|Corner Bar|The Corner Store|Cafe Cluny|Café Cluny|Buvette|Balthazar|Pastis|Time Again
Death & Co|Clemente Bar|Martiny's|Sip & Guzzle|Dear Irving|Patent Pending|Bathtub Gin|Apotheke|Sunken Harbor Club|Bar Goto|Mace|Odo Lounge|Saint Tuesday|Paradise Lost|Temple Bar|Le Boudoir|The Campbell|Beauty & Essex|Superbueno|Overstory|Angel's Share|Dante|Clover Club|Leyenda|Bar Kabawa|Ray's|Milady's|Swan Room|The Portrait Bar|Bar Madonna|Raines Law Room|The Raines Law Room|PDT / Please Don't Tell|PDT
Guardian|Westlight|Harriet's Rooftop|Electric Lemon|Peak|Panorama Room|The Fleur Room|Magic Hour|The Skylark|JIMMY|Summerly|Dear Irving on Hudson|Manhatta|The Roof at Public Hotel|The Crown|Ophelia|Mr Purple|RH Rooftop Restaurant|Overstory
Eleven Madison Park|Le Bernardin|Daniel|The Modern|Gramercy Tavern|Jeju Noodle Bar|Tuome|Le Coucou|Rezdôra|Oxomoco|Semma|Torrisi|Corima|Bridges|Cote|Crown Shy|Saga|Le Pavillon|Essential by Christophe|63 Clinton|Family Meal at Blue Hill|Francie|The Four Horsemen|Jua|Kochi|Mari|Oiji Mi|Atoboy|César|Kabawa|Borgo|Maison Passerelle|Dhamaka|Russ & Daughters Cafe|Ugly Baby|Bungalow|Coqodaq|Bánh Anh Em|Laliko|Atla|Una Pizza Napoletana|Roberta's|Superiority Burger|Win Son|Zaab Zaab|Miss Ada|Nami Nori|Noreetuh|Pinch Chinese|Potluck Club|Little Alley|MáLà Project|Sami & Susu|Shalom Japan|Haenyeo|Yellow Rose|Sobre Masa|Alta Calidad|Rolo's|Soda Club|C as in Charlie|8282
Carbone|Don Angie|San Sabino|Lilia|Misi|I Sodi|L'Artusi|Tatiana by Kwame Onwuachi|Hawksmoor|Bad Roman|Raoul's|Minetta Tavern|Frenchette|Chez Fifi|Lucien|Indochine|Gage & Tollner|Frankies 457 Spuntino|Atoboy|Passerine|Adda|Naks|Masalawala & Sons|Shukette|Ilili|Uncle Lou|Szechuan Mountain House|Han Dynasty|Nom Wah Tea Parlor|Ha's Đặc Biệt|Mắm|Madame Vo|Pig & Khao|Fish Cheeks|Llama San|Contento|Marea|Ai Fiori|Il Buco|Rubirosa|Claudette|Charles Pan-Fried Chicken|Fausto|Sadelle's|Jack's Wife Freda|Sunday in Brooklyn|Five Leaves|Sant Ambroeus|La Mercerie|Clinton St. Baking Company|Ruby's Cafe|Cookshop|Rosemary's|Bubby's|Red Rooster|Loulou|Zizi|Lafayette Grand Café|Sweet Chick
Catch NYC / Catch Steak|Sadelle's|Lure Fishbar|Casa Cruz|Nine Orchard|Jean's|Pebble Bar|Little Sister|Elio's|The Bar at Baccarat|Aman New York|Cipriani Downtown / Cipriani Dolci""".replace("\n","|").split("|")
T = """Per Se|Atomix|Aska|Atera|Chef's Table at Brooklyn Fare|Odo|Sushi Noz|Bōm|Yamada|Meju|Icca|Shion 69 Leonard Street|Noz 17|Nōksu|Bar Miller|Restaurant Yuu|Yingtao|Yoshino|Kosaka|Tsukimi|Shota Omakase|Jōji|Noda|Muku|Huso|Sushi Sho|Jungsik|Joo Ok|Torien|L'Abeille|Dirt Candy|Sushi Nakazawa|Frevo|Masa""".split("|")
O = """Jean-Georges|Attaboy|Tavern on the Green|Barbetta|Rolf's German Restaurant|Serafina|Scarpetta|Tamarind|Milos|Avra|Nobu Downtown / Nobu 57|Mr Chow|Philippe Chow|Il Mulino|Buddakan|Indian Accent|Keens Steakhouse|Bar SixtyFive at Rainbow Room|Salon de Ning|Castell|Refinery Rooftop|230 Fifth Rooftop Bar|Serra by Birreria|La Birreria / Serra by Birreria|Jacob's Pickles|Victor's Cafe|Sarabeth's|The Smith|Aquavit|Gabriel Kreuther|Peter Luger|Naya Mezze & Grill|Spice Symphony|Drunken Munkey|Baar Baar|Elea|Iris|Ootoya|Tempura Matsui|Sushi Yasaka|Balaboosta|Locanda Verde|Café Carlyle""".split("|")
S = """Tao Uptown / Tao Downtown|Lavo Italian Restaurant|Cathédrale|Nusr-Et|Marquee|Wiggle Room|Tao Downtown Nightclub|Nebula|Somewhere Nowhere|Le Bain|Le Bain / Boom Boom Room|The Boom Boom Room|PHD|PHD Rooftop Lounge|Employees Only|Dead Rabbit|Zero Bond|Casa Cipriani|San Vicente Bungalows NYC|Chez Margaux|The Nines|Harbor NYC|Goldbar|Paul's Baby Grand|Paul's Casablanca|The Box|Musica|Gansevoort Rooftop|Arlo Roof Top|Nubeluz|Bagatelle""".split("|")
W = """Katz's Delicatessen|Katz's|Little Branch|The Back Room|Katana Kitten|Double Chicken Please|Amor y Amargo|Fresh Kills|Long Island Bar|Bemelmans Bar|McSorley's Old Ale House|Ear Inn|White Horse Tavern|Old Town Bar|Pete's Tavern|Jimmy's Corner|Rudy's Bar & Grill|Sunny's Bar|Skinny Dennis|Union Pool|Tørst|Proletariat|Spuyten Duyvil|Blind Tiger|Other Half|Copper & Oak|Holiday Cocktail Lounge|Marie's Crisis|Thai Diner|Ippudo|Totto Ramen|Ichiran|Joe's Shanghai|Dim Sum Go Go|Tim Ho Wan|Wu's Wonton King|Nan Xiang Xiao Long Bao|Los Tacos No.1|Taqueria Ramírez|Birria-Landia|L'Industrie Pizzeria|Lucali|Scarr's Pizza|Joe's Pizza|Prince Street Pizza|Di Fara|Mamoun's Falafel|Xi'an Famous Foods|Hometown Bar-B-Que|Barney Greengrass|Veselka|Tom's Restaurant|Lexington Candy Shop|Bluestone Lane|Two Hands|Westville|Cheburechnaya|Kabab King|Tompkins Square Bagels|Apollo Bagels|Utopia Bagels|Momofuku Noodle Bar|Superiority Burger|Cheeky Sandwiches|Court Street Grocers|Defonte's|Frankel's Delicatessen|Peter Pan Donut & Pastry|Punjabi Deli|Halal Guys|Cafe Sabarsky""".split("|")
PLAT={}
for lst,tag in ((O,'OpenTable'),(S,'SevenRooms'),(W,'Walk-in'),(T,'Tock'),(R,'Resy')):
    for n in lst:
        n=n.strip()
        if n: PLAT[n]=tag
def lookup(name):
    if name in PLAT: return PLAT[name]
    base=name.split(' (')[0].strip()
    return PLAT.get(base)
