# -*- coding: utf-8 -*-
ITINS = [
 {"key":"one-day","title":"One day","deck":"North Beach to the Mission, on foot and one Muni ride. Focaccia at nine, a three-star at eight.",
  "who":"One day, mostly walkable if you like hills. Book one dinner.",
  "book":"Book one thing: dinner at Californios (Tock) — or Rintaro if the three-star is gone.",
  "days":[{"label":"The day","stops":[
   ("8:30","Liguria Bakery (North Beach)","Focaccia, cash, wrapped in paper — go before ten or it's gone. Then a cappuccino at Caffè Trieste, where the West Coast's first espresso machine was installed in 1956."),
   ("10:00","North Beach & Chinatown","City Lights, the alleys, the Golden Gate Fortune Cookie Factory in Ross Alley. Good Mong Kok for a bag of dim sum through the window."),
   ("12:00","Swan Oyster Depot (Nob Hill)","The counter since 1912: crab Louie, a half-dozen oysters, sea urchin if they have it. Cash only; the line starts before eleven. Worth it."),
   ("2:00","The Mission","Walk Valencia; Dandelion Chocolate for the factory; Bi-Rite Creamery for a scoop in Dolores Park."),
   ("4:00","Trick Dog (Mission)","Whatever this season's menu is. Walk-in; go early. Then True Laurel next door — 50 Best."),
   ("6:00","Zeitgeist (Mission)","One beer in the garden, because it's the city's living room."),
   ("8:00","Californios (Mission) ★★★","Val Cantu's counter — the first three-star Mexican restaurant in the world, promoted in June. Tock, weeks out. Backup: Rintaro (izakaya, Bib, Resy), Flour + Water (Bib, Resy) or the Morris for the duck (Bib, Resy)."),
   ("10:30","Bar Part Time (Mission)","Records, natural wine, a dance floor that appears. Walk-in."),
  ]}]},
 {"key":"three-day","title":"Three days","deck":"The city, then the water, then the Richmond and the Sunset. Fog permitting.",
  "who":"A long weekend. Day one is the one-day plan; day two is the Embarcadero and Nob Hill; day three goes west to the ocean.",
  "book":"Book three dinners the day reservations open: Californios, Lazy Bear or Saison, and Mister Jiu's.",
  "days":[
   {"label":"Day 1 · North Beach to the Mission","stops":[("All day","Follow the one-day plan","Liguria, Chinatown, Swan, the Mission, Trick Dog, Zeitgeist, Californios, Bar Part Time.")]},
   {"label":"Day 2 · The water & Nob Hill","stops":[
     ("8:30","Ferry Building","Saturday market if it's Saturday; otherwise Blue Bottle, Acme bread, and Hog Island's oysters at the counter when it opens."),
     ("11:00","The Embarcadero","Walk south under the bridge; Red's Java House on Pier 30 for a burger on the pier if you're early-hungry."),
     ("1:00","Tadich Grill (FiDi)","California's oldest restaurant, 1849: cioppino or sand dabs at the counter. Walk-in; the wait is the ritual. Or Sam's Grill for the curtained booths."),
     ("3:30","Nob Hill","The cable car up California Street; the Tonga Room's rainstorm at the Fairmont for one mai tai; Bob's Donuts on the way down."),
     ("5:30","Top of the Mark or Big 4","The view, or the piano. Both walk-in early."),
     ("7:30","Lazy Bear (Mission) ★★ or Saison (SoMa) ★★","Lazy Bear for the dinner-party format (Tock); Saison for the hearth (Tock). Backup: Nisei ★ (Russian Hill; Tock) or Sons & Daughters ★ (Nob Hill; Tock)."),
     ("10:30","Pacific Cocktail Haven (Union Square)","50 Best; walk-in late. Or Bourbon & Branch with the password."),
   ]},
   {"label":"Day 3 · West","stops":[
     ("9:00","Arsicault (Inner Richmond)","The croissant that won the country. Walk-in; the line moves."),
     ("11:00","Golden Gate Park","The de Young tower for the free view, the Japanese Tea Garden, then Andytown at the ocean for a Snowy Plover."),
     ("1:00","Outerlands (Outer Sunset)","Lunch a block from the beach. Or Hook Fish Co for a fish sandwich to eat on the dunes."),
     ("3:30","Tommy's Mexican (Outer Richmond)","Julio Bermejo's margarita — the one every bar copies — with a plate of tacos. Walk-in."),
     ("5:30","Chinatown","Li Po for a Chinese mai tai, Mr. Bing's for dice, Cold Drinks Bar upstairs at China Live if you want the good version."),
     ("7:30","Mister Jiu's (Chinatown) ★","Brandon Jew's Cantonese-Californian in the old Four Seas banquet hall. Resy, 30 days. Backup: Four Kings (his alumni, walk-in early) or Z & Y (Sichuan, Bib)."),
     ("10:00","Moongate Lounge (upstairs)","The cocktail bar above Mister Jiu's. Then Vesuvio for a nightcap where the Beats drank."),
   ]},
  ]},
 {"key":"five-day","title":"Five days","deck":"The three-day plan, plus a day across the bay and a day for Wine Country or the counters.",
  "who":"Enough time to leave the city: Berkeley and Oakland, Tomales Bay or Yountville, and the tasting counters that need weeks.",
  "book":"Set alarms for Californios, Benu or Atelier Crenn (Tock), and — if you're driving — the French Laundry.",
  "days":[
   {"label":"Days 1–3","stops":[("All","Follow the three-day plan","North Beach and the Mission, the water and Nob Hill, the Richmond and the Sunset.")]},
   {"label":"Day 4 · Across the bay","stops":[
     ("9:00","BART to Berkeley","Cheese Board Collective — one pizza a day, a line, a jazz trio — or Boichik for the bagel the Times called America's best."),
     ("11:30","Chez Panisse Café (Berkeley)","Upstairs, à la carte, Alice Waters' room since 1971. Resy; lunch is the accessible seat. Then Vik's Chaat if you're still hungry."),
     ("2:30","Oakland","Temescal: Bakesale Betty's fried chicken sandwich, Ordinaire for a glass. Grand Lake if it's Saturday, for the market."),
     ("5:00","Viridian or Bar Shiru (Oakland)","Asian-American cocktails, or the listening bar. Walk-in early."),
     ("7:30","Commis (Oakland) ★★ or Burdell (Oakland)","Commis for James Syhabout's counter (Tock); Burdell for Geoff Davis's Black Southern cooking, a James Beard finalist (Resy). Backup: Nyum Bai (Cambodian, Bib) or Snail Bar (wine, Bib)."),
     ("10:00","The Kon-Tiki (Oakland)","Tiki, then BART home before midnight — check the schedule."),
   ]},
   {"label":"Day 5 · North, or the counters","stops":[
     ("9:00","Drive north — Tomales Bay","Hog Island Oyster Farm at Marshall: shuck your own on the picnic tables (reserve). The Marshall Store next door if you'd rather be served. Cash-friendly."),
     ("1:00","Or: Yountville","Bouchon Bakery for a macaron, Ad Hoc for fried chicken if it's Monday, La Calenda for Keller's Mexican (Bib). The French Laundry is a Tock ticket, two months out, and worth the effort once."),
     ("4:30","Sausalito on the way back","Fish. on the dock (cash), then the ferry into the city at sunset — the best $14 view in the Bay."),
     ("6:30","Charmaine's (SF Proper)","One drink on the roof, Market Street below."),
     ("8:00","Benu ★★★ or Atelier Crenn ★★★","Benu for Corey Lee's Korean-inflected tasting (Tock); Atelier Crenn for Dominique Crenn's poem of a menu (Tock). Both weeks out. Alternative: Quince ★★★ (Tock) or Acquerello ★★ (Resy; the room since 1989)."),
     ("11:00","Bob's Donuts (Nob Hill)","Open 24 hours. An apple fritter for the road."),
   ]},
  ]},
]
GOTCHAS = [
 ("Tock, Resy, and the two-month counters.", "Benu, Atelier Crenn, Quince, Californios, Lazy Bear, Saison and the French Laundry sell tickets on Tock, often two months out and non-refundable. Resy runs the neighborhood rooms, 30 days out. Set alerts for both."),
 ("Cash at the institutions.", "Swan Oyster Depot, Liguria, Saigon Sandwich, Fish. in Sausalito, Golden Gate Fortune Cookie and most of Chinatown's bakeries are cash-only or cash-first. Carry $80 on the first day."),
 ("The fog is a neighborhood.", "The Sunset and Richmond can be 15 degrees colder than the Mission on the same afternoon. Dress in layers; the Embarcadero is windier than it looks. 'Karl' is the fog's name and locals will use it."),
 ("Tip 20%; watch the SF Mandate line.", "Many restaurants add a 5–6% 'SF Mandate' or health surcharge to cover city ordinances — it's not the tip, and it's legal. Sales tax on meals is 8.625%. Read the bill."),
 ("Hills, and how to move.", "Muni and the cable cars take a contactless tap; BART to Oakland and Berkeley runs until about midnight. Rideshares are reliable but expensive at 2am. Nob Hill and Russian Hill are steeper than any map admits."),
 ("Monday is dark, and so is much of Sunday.", "Most starred rooms close Sunday and Monday — Californios, Lazy Bear, Saison, Sons & Daughters all do. Chinatown, the Mission's taquerias and the Ferry Building run seven days."),
 ("The burrito rules.", "A Mission burrito is foil-wrapped, rice and beans inside, and eaten standing. El Farolito and La Taqueria (no rice, and a Bib) are the two ends of the argument; order carne asada or al pastor at either and don't ask for a bowl."),
 ("Sourdough and the Irish coffee.", "Boudin has baked the same mother dough since 1849; the bread bowl is for tourists but the loaf is real. The Buena Vista invented America's Irish coffee in 1952 and still makes 2,000 a day — the morning is the time."),
 ("Use the Amex credit like a local.", "Platinum $100 per quarter, Gold $50 twice a year, at any Resy or Tock venue showing the 'Resy Credit eligible' badge. A prepaid Tock ticket at a three-star is the easiest use of it."),
 ("Anything marked verify, verify.", "San Francisco lost Anchor Brewing, Liholiho, Aphotic, Bar Agricole, Mission Chinese and the Cliff House within a few years. A minute on Resy or Google before you climb a hill."),
 ("The Chinatown vocabulary.", "Chinese mai tai (Li Po): rum, a secret mix, and a kick. Dim sum to-go (Good Mong Kok): point, pay cash, eat in Portsmouth Square. Salt-and-pepper crab (R&G): the dish to order once."),
 ("One for the road.", "SFO's International Terminal has a Boudin and a Tartine; Terminal 2 has an Andale and, if you're lucky, a Boichik. The BART ride from the city is the cheapest way there and takes half an hour."),
]
