# -*- coding: utf-8 -*-
ITINS = [
 {"key":"one-day","title":"One day","deck":"Pike Place to Capitol Hill, on foot. Oysters at noon, a Beard finalist at eight.",
  "who":"One day, walkable if you accept the hills. Book one dinner.",
  "book":"Book one thing: dinner at Atoma (Tock) — or the Walrus if it's gone.",
  "days":[{"label":"The day","stops":[
   ("8:00","Café Allegro (University District) or Espresso Vivace (Capitol Hill)","The first espresso bar in Seattle (1975), or the one that invented latte art. Pick one; walk-in."),
   ("9:30","Pike Place Market","Before the crowds: Piroshky's line, the Crumpet Shop, a hum bow at Mee Sum, the fish throwers. Oriental Mart in the arcade for a Filipino breakfast — a James Beard America's Classic in a stall."),
   ("12:00","Emmett Watson's or Taylor Shellfish (Pike Place / Capitol Hill)","A dozen Kumamotos and Shigokus, the Sound's oysters at their source. Walk-in."),
   ("2:00","Capitol Hill","Melrose Market: Café Suliman (Beard Emerging Chef semifinalist) for a late lunch, Temple Pastries for a pastry, Elliott Bay Book Co."),
   ("4:00","Zig Zag Café (the Hillclimb)","Where Murray Stenson made the Last Word famous. Walk-in; then the Nest on the Thompson's roof for the Sound at golden hour."),
   ("6:00","Canon (Capitol Hill)","The largest spirits collection in the Western Hemisphere; order from the book. Walk-in early; the wait builds."),
   ("8:00","Atoma (Wallingford) or The Walrus and the Carpenter (Ballard)","Atoma for Johnny Courtney's snack-sized starters — a 2026 Beard finalist and Restaurant of the Year (Tock); the Walrus for Renee Erickson's oyster bar (walk-in, put your name down at 4 and wander Ballard). Backup: Musang (Filipino; Resy) or Homer (Beacon Hill; Resy)."),
   ("10:30","Rob Roy (Belltown)","Anu Apte's bar, a Beard semifinalist for cocktail service. Then Dick's for a Deluxe on the way home, cash, since 1954."),
  ]}]},
 {"key":"three-day","title":"Three days","deck":"Downtown and Capitol Hill, then Ballard and Fremont, then Beacon Hill and the ID. One neighborhood cluster a day.",
  "who":"A long weekend. Day one is the one-day plan; day two goes north across the ship canal; day three goes south.",
  "book":"Book three dinners the day reservations open: Atoma, Canlis, and Archipelago or Surrell.",
  "days":[
   {"label":"Day 1 · Downtown & Capitol Hill","stops":[("All day","Follow the one-day plan","Coffee, the market, oysters, Melrose Market, Zig Zag, Canon, Atoma, Rob Roy.")]},
   {"label":"Day 2 · Ballard & Fremont","stops":[
     ("9:00","Cafe Besalu (Ballard)","The croissant Seattle argues about. Walk-in; the line moves. Larsen's for a kringle on the way out."),
     ("11:00","Ballard","The Locks and the fish ladder, the Sunday market if it's Sunday, Un Bien for the Caribbean roast pork sandwich — the original family, the better sandwich."),
     ("1:30","Fremont","Theo Chocolate's factory, the Troll, Milstead & Co for the multi-roaster pour-over, Sea Wolf for a morning bun at lunch."),
     ("3:30","Fremont Brewing","The urban beer garden, a Lush IPA, a pretzel. Then Brouwer's for the Belgian list if it's raining."),
     ("6:00","Westward (Lake Union)","The fire pit on the water, the Needle across the lake, one drink before dinner. Resy."),
     ("8:00","Canlis (Queen Anne)","Since 1950 — the valet, the view, the tasting menu. Tock, weeks out; jackets not required but everyone tries. Backup: the Whale Wins (Fremont; Resy) or Copine (Ballard; Resy)."),
     ("10:30","Hazlewood (Ballard) or the Backdoor at Roxy's (Fremont)","Hazlewood is tiny and perfect; the Backdoor is through the diner. Either walks in."),
   ]},
   {"label":"Day 3 · South","stops":[
     ("9:30","Jade Garden or Harbor City (Chinatown–ID)","Dim sum from the carts. Walk-in; arrive before ten on a weekend."),
     ("11:30","Chinatown–ID","Uwajimaya's food hall, Maneki's room since 1904 (look, then book for dinner another time), Hood Famous for ube cheesecake, Tai Tung for Bruce Lee's booth."),
     ("1:30","Pho Bac Súp Shop (Chinatown–ID)","The Pham sisters' boat — two-time Beard Outstanding Restaurateur finalists — for the pho and the whole story. Walk-in."),
     ("3:30","Beacon Hill","Bar del Corso for a pizza to share, then a look at Musang and Homer's block — both Beard semifinalists, both here."),
     ("5:30","ShibShib (Chinatown–ID)","Ahmed Suliman's new cocktail bar, opened the week of the Beard awards. Walk-in."),
     ("7:30","Archipelago (Hillman City) or Surrell (Madrona)","Archipelago for the Verzosas' Filipino tasting menu — Outstanding Chef semifinalist (Tock, weeks out); Surrell for Aaron Tekulve's counter — the other 2026 finalist (Tock). Backup: Musang (Resy) or Off Alley (8 seats; Tock)."),
     ("10:00","The Royal Room (Columbia City)","Jazz, late. Or Clock-Out Lounge on Beacon Hill for the pizza and the bands."),
   ]},
  ]},
 {"key":"five-day","title":"Five days","deck":"The three-day plan, plus a day on the water and a day for the oyster farms and the islands.",
  "who":"Enough time to leave the city: a ferry, an oyster farm on the Hood Canal, and Whidbey Island's new tasting room.",
  "book":"Set alarms for Canlis, Archipelago, Surrell, and — if you're driving north — Passage on Whidbey.",
  "days":[
   {"label":"Days 1–3","stops":[("All","Follow the three-day plan","Downtown and Capitol Hill, Ballard and Fremont, the South End.")]},
   {"label":"Day 4 · The water","stops":[
     ("9:00","Portage Bay Cafe (South Lake Union)","The pancake toppings bar. Walk-in; the wait is real."),
     ("11:00","The Bainbridge ferry","Thirty-five minutes across the Sound; the skyline behind you. Blackbird Bakery and Hitchcock Deli in Winslow, then the ferry back at golden hour."),
     ("3:00","West Seattle water taxi","From Pier 50 to Alki: Marination Ma Kai on the dock for a Hawaiian-Korean plate with the skyline across the bay."),
     ("5:00","Alki","Husky Deli for ice cream since 1932, a walk on the beach, Salty's if you want the view with a glass."),
     ("7:30","Il Nido (Alki bathhouse) or Tomo (White Center)","Il Nido for Mike Easton's pasta in a 1930s bathhouse (Resy); Tomo for Brady Williams — Seattle's last Beard winner — and his counter (Tock). Backup: Mashiko for sustainable sushi (Resy)."),
     ("10:00","Beveridge Place Pub (West Seattle)","Beer and a board game. Then the water taxi's last run — check the time — or a car."),
   ]},
   {"label":"Day 5 · Oysters, or the islands","stops":[
     ("9:00","Drive south — Hood Canal","Hama Hama Oyster Saloon at Lilliwaup: oysters shucked at the farm, a fire, the canal. Two hours each way; worth it once. Taylor Shellfish's farm store in Shelton on the way back."),
     ("1:00","Or: Whidbey Island","The Mukilteo ferry, then Passage at the Inn at Langley — Johnny Spero's Pacific Northwest tasting menu, the D.C. star's new room (Tock; stay the night if you can)."),
     ("5:00","Back in the city: Mbar (South Lake Union)","The Needle at sunset from the roof. Resy."),
     ("6:30","Roquette (Belltown)","A Beard semifinalist for Outstanding Bar, six seats at the counter. Walk-in early."),
     ("8:00","Sushi Kashiba (Pike Place) or Taneda (Capitol Hill)","Shiro Kashiba's counter at the market (Tock; the walk-in bar seats go at 5:00); Taneda's eight-seat kaiseki (Tock). Alternative: Wataru's edomae counter in Ravenna (Tock)."),
     ("11:00","Fran's at the airport, tomorrow","The salted caramels are the last stop. Tonight: Dick's, cash, one more Deluxe."),
   ]},
  ]},
]
GOTCHAS = [
 ("Tock for the counters, Resy for the rooms.", "Canlis, Archipelago, Surrell, Atoma, the Herbfarm, Kashiba, Taneda and Wataru sell tickets on Tock, often weeks out. The Walrus doesn't take reservations — put your name down at 4pm and wander Ballard. Resy runs the rest, 30 days out."),
 ("The ferries are the transit and the attraction.", "Bainbridge from Colman Dock, West Seattle by water taxi from Pier 50, Whidbey from Mukilteo. Walk-on fares are cheap; car lines are not. Check the last sailing before dinner."),
 ("Cash at the counters.", "Dick's, Thai Tom, Un Bien, Tat's, the market's stalls and most of the ID's bakeries are cash-first. Carry $60 on the market day."),
 ("Tip 20%; the minimum wage is the highest in the country.", "Seattle's $20+ minimum means some restaurants have dropped tipping for a service charge (Canlis, among others) — it's on the menu. Sales tax on meals is 10.35%. Read the bill."),
 ("It rains, and the city ignores it.", "October to May, most days. Rooftops and beer gardens close or empty; the Nest and Mbar have heaters. Nobody carries an umbrella; a hood is the local uniform. Summer — July to September — is when the city is the best in the country."),
 ("Last call is 2am; the light rail runs until 1.", "Link light rail connects the airport, the ID, Capitol Hill, the U District and Northgate; buses do the rest. Ballard and Fremont after midnight are a car. The ORCA card is optional — tap a contactless card."),
 ("Monday is dark.", "Atoma, Archipelago, Surrell, Canlis and most chef rooms close Sunday and/or Monday. The market, the ID and the pho shops run seven days."),
 ("The oyster vocabulary.", "Kumamoto: small, sweet, from Humboldt Bay. Shigoku: Taylor's tumbled Pacific, deep-cupped. Olympia: the tiny native, coppery. Order a dozen mixed and a Washington white; the Sound's oysters are best from October to April."),
 ("Use the Amex credit like a local.", "Platinum $100 per quarter, Gold $50 twice a year, at any Resy or Tock venue showing the 'Resy Credit eligible' badge. A Canlis ticket on Tock is the easiest use of it."),
 ("Anything marked verify, verify.", "Seattle lost Bar Melusine, Sitka & Spruce, Salare, Il Corvo, the London Plane and the Willows Inn within a few years. A minute on Resy or Google before you take a ferry."),
 ("Coffee: the lineage.", "Café Allegro (1975) was the first espresso bar; Starbucks' first store is at 1912 Pike Place (the line is the tourists'); Vivace invented the rosetta; Victrola, Milstead and Analog are where the city drinks now. Ordering a 'tall' anywhere but Starbucks will be noted."),
 ("One for the road.", "Sea-Tac has a Beecher's, an Ivar's, a Fran's and a Sub Pop store. Buy the caramels; skip the airport chowder."),
]
